name: Python application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Decode service account key
      run: |
        echo ${{ secrets.SERVICE_ACCOUNT_KEY }} | base64 --decode > service-account-file.json

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run script
      run: python rss_to_blogger.py
      env:
        BLOGGER_BLOG_ID: ${{ secrets.BLOGGER_BLOG_ID }}
        RSS_FEED_URLS: ${{ secrets.RSS_FEED_URLS }}
        SERVICE_ACCOUNT_FILE: ${{ github.workspace }}/service-account-file.json
